### PR TITLE
fix(registry): fixes filtering registry entries by SDG

### PR DESCRIPTION
**Pull request by sfishel18**
- updates logic to compute SDG filter class names on item elements
- ~~updates project setup instructions~~ (edit: moved to a separate PR)

### CODE REVIEW

**Comment by sfishel18** [comment]
👋 hello! i love the project and the mission behind it. i noticed when browsing the registry that the checkboxes to filter by SDG don't always work correctly, so the PR is a small fix to get that working. i also hit a few snags with the setup instructions so i updated them to what worked for me.

**Comment by gazdagergo** [comment]
> 👋 hello! i love the project and the mission behind it. i noticed when browsing the registry that the checkboxes to filter by SDG don't always work correctly, so this PR is a small fix to get that working. i also hit a few snags with the setup instructions so i updated them to what worked for me.

Thanks SImon, and welcome to the contributor hub! Let me check your changes and I get back to you soon! I'm super excited to have you on board.

**Comment by sfishel18** [comment]
> > * updates logic to compute SDG filter key based on clicked checkbox
> > * updates project setup instructions
> 
> Please provide two separate PRs for the two fixes.

👍 done

**Comment by law909** [comment]
> > > * updates logic to compute SDG filter key based on clicked checkbox
> > > * updates project setup instructions
> > 
> > 
> > Please provide two separate PRs for the two fixes.
> 
> 👍 done

Thank you!

**Review by nathanfletcher — APPROVED** [review]

**Pull request merged**
